### ISSUE TITLE
Implement a HTTP client to query IANA's RDAP service

### ISSUE THREAD

**Issue by MendelGusmao** [registrobr/rdap-client#1]
References:

- http://www.iana.org/protocols (Section RDAP)
- http://tools.ietf.org/html/rfc7484#section-8

**Comment by joaopetreli** [comment]
Things to be considered:
- Nowadays there's no services registered. Maybe the client should fall back to registro.br RDAP server by default.
 - Use the HTTP cache header to check if the files has been modified.
