### ISSUE TITLE
Non-existent Entries or RDAP URL Values

### ISSUE THREAD

**Issue by joaopetreli** [registrobr/rdap-client#11]
The registries may not contain the requested value.  In these cases, there is no known RDAP server for that requested value, and the client SHOULD provide an appropriate error message to the user.

https://tools.ietf.org/html/rfc7484#section-7

**Comment by MendelGusmao** [comment]
Already doing this.
See https://github.com/registrobr/rdap-client/blob/master/bootstrap/client.go#L85-L87
