### ISSUE TITLE
Missing license and something else...

### ISSUE THREAD

**Issue by kemelzaidan** [registrobr/rdap-client#14]
The app is missing its license in order to be packaged to any distributions. Besides that, my golang knowledge might be a bit outdated, but I believe you don't need to commit the vendor folder into the repository, since it will be downloaded by the `go mod` command...

Please, update it with a license term, since I'm interested in packaging it to Arch.

**Comment by rafaeljusto** [comment]
> The app is missing its license in order to be packaged to any distributions

👍 I will leave this one for the engineering team.

> you don't need to commit the vendor folder into the repository

I would agree if this was a library, but for an app, the idea of using the `vendor` folder is to guarantee that dependencies won't vanish and break the system out of the blue. An elegant alternative would be using [`GOPROXY`](https://go.dev/ref/mod#module-proxy), but it requires some extra setup.
