### ISSUE TITLE
Response "forbidden" for all .br domains?

### ISSUE THREAD

**Issue by safernet** [registrobr/rdap-client#7]
Hello everyone,

Thanks for the great library!

Is it expected that the client returns "forbidden" for all .br domains? At least it happens to all .br we tried.

Thanks in advance,

**Comment by rubenskuhl** [comment]
That depends on whether the IP address making the request is blocked or not. Trying doing a WHOIS request from the same client IP address; if it gets a forbidden response, then you know what the problem is.

**Comment by safernet** [comment]
Thanks! Yeah, it fails for a WHOIS request from that same client too. Weird that it also fails from a couple different servers with fixed IP from different geographic locations, which didn't make any WHOIS request recently. It works from a third server, though.

**Comment by rubenskuhl** [comment]
> Thanks! Yeah, it fails for a WHOIS request from that same client too. Weird that it also fails from a couple different servers with fixed IP from different geographic locations, which didn't make any WHOIS request recently. It works from a third server, though.

There are two ways an IP can be blocked:
- Because it specifically made many requests
- Because it is part of the IP block of an upstream provider that made many requests

What you described sounded like the later, not the former.

**Comment by safernet** [comment]
Right... OK, thanks for clarifying! I guess it's clear it's not an issue with the `rdap-client`, so I'll just close this ticket.
