### ISSUE TITLE
# rdap-client 137.54.45.4 returning "forbidden"

### ISSUE THREAD

**Issue by 65007** [registrobr/rdap-client#9]
# rdap-client 137.54.45.4
forbidden

While other CLI RDAP clients (and also WHOIS) does return data

**Comment by rafaeljusto** [comment]
Hey Nicolas!

Running it here now I did get results:
```
./rdap-client 137.54.45.4               

inetnum:       137.54.0.0/16
handle:        NET-137-54-0-0-1
parent-handle: NET-137-0-0-0-0
start-address: 137.54.0.0
end-address:   137.54.255.255
ip-version:    v4
name:          UNIVERSITY-OF-VIRGINIA
type:          DIRECT ALLOCATION
status:        active
created:       19891101
changed:       20130422

handle:   ABUSE124-ARIN
roles:    abuse
person:   Abuse Team
e-mail:   abuse@virginia.edu
address:  ISPRO, P.O. Box 400898, Charlottesville, VA, 22904-0898, United States
phone:    +1-434-243-8707
created:  20021123
changed:  20171128

handle:   UVA
roles:    registrant
person:   University of Virginia
address:  University of Virginia, ITC, P.O. Box 400324, Charlottesville, VA, 22904-4324, United States
created:  19871214
changed:  20150316

handle:   ITS31-ARIN
roles:    administrative, technical, noc
person:   ITS
e-mail:   networks@virginia.edu
address:  2015 Ivy road, Charlottesville, VA, 22903, United States
phone:    +1-434-924-0632
created:  20120228
changed:  20190917
```

The forbidden error is returned when some HTTP servers return the HTTP status 403 (Forbidden) ([code reference](https://github.com/registrobr/rdap/blob/c540416760a7d5923475b3f09cad39337a1a4331/transport.go#L206)). So maybe it was an intermittent error? The server being requested was `https://rdap.arin.net/registry/ip/137.54.45.4`.

**Comment by cesarkuroiwa** [comment]
For some reason, once in a while, the ARIN server returns Forbidden. Still investigating on that

**Comment by 65007** [comment]
Could there be something in the HTTP header (as HTTP may return forbidden
if the client sends some "incorrect" header)?

I'm just guessing what the issue could be. I've tested from two different
clients (one in Uruguay and one in the US and got the same forbidden
response).
Also I've tested other RDAP clients and they return the correct info... as
well as whois.

Hope you're able to figure out what's going on.
By the way, very good job with rdap-client !

Nico

**Comment by rafaeljusto** [comment]
@cesarkuroiwa I think we are missing setting the `User-Agent` HTTP header [here](https://github.com/registrobr/rdap/blob/c540416760a7d5923475b3f09cad39337a1a4331/transport.go#L193).
```
req.Header.Set("User-Agent", "registrobr-rdap")
```

**Comment by rafaeljusto** [comment]
For the RDAP client if I add the `User-Agent` HTTP header it works, otherwise it's returning 403 now (wasn't happening Yesterday). The response body for 403s:
```html
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /registry/ip/137.54.45.4
on this server.</p>
</body></html>
```

Curiously it's not the same when running `curl`, it works with or without the `User-Agent`:
> curl -v -i -H 'User-Agent:' -H 'Accept:' 'http://rdap.arin.net/registry/ip/137.54.45.4'
```
*   Trying 2001:500:31::160...
* TCP_NODELAY set
* Connected to rdap.arin.net (2001:500:31::160) port 80 (#0)
> GET /registry/ip/137.54.45.4 HTTP/1.1
> Host: rdap.arin.net
> Accept: */*
> 
< HTTP/1.1 200 
HTTP/1.1 200 
< Date: Fri, 04 Jun 2021 18:08:59 GMT
Date: Fri, 04 Jun 2021 18:08:59 GMT
< Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
< Content-Type: application/rdap+json
Content-Type: application/rdap+json
< Access-Control-Allow-Origin: *
Access-Control-Allow-Origin: *
< Transfer-Encoding: chunked
Transfer-Encoding: chunked
...
```

🤔 Maybe the Go client is doing something else?

**Comment by cesarkuroiwa** [comment]
Apparently, if you don't set anything, the Go client sends the User-Agent header "Go-http-client/1.1", which for some reason the server doesn't like:

```
% curl -v -H User-Agent:Go-http-client/1.1 -H Accept:application/rdap+json 'http://rdap.arin.net/registry/ip/137.54.45.4'
*   Trying 199.212.0.160:80...
* TCP_NODELAY set
*   Trying 2001:500:a9::160:80...
* TCP_NODELAY set
* Immediate connect fail for 2001:500:a9::160: Network is unreachable
*   Trying 2001:500:31::160:80...
* TCP_NODELAY set
* Immediate connect fail for 2001:500:31::160: Network is unreachable
*   Trying 2001:500:13::160:80...
* TCP_NODELAY set
* Immediate connect fail for 2001:500:13::160: Network is unreachable
* Connected to rdap.arin.net (199.212.0.160) port 80 (#0)
> GET /registry/ip/137.54.45.4 HTTP/1.1
> Host: rdap.arin.net
> User-Agent:Go-http-client/1.1
> Accept:application/rdap+json
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< Date: Fri, 04 Jun 2021 20:35:57 GMT
< Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
< Content-Length: 225
< Content-Type: text/html; charset=iso-8859-1
< 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /registry/ip/137.54.45.4
on this server.</p>
</body></html>
* Connection #0 to host rdap.arin.net left intact

```

**Comment by rafaeljusto** [comment]
@65007 Thanks for reporting the issue, this should be fixed now on the latest version of the tool.

For reference: 
https://github.com/registrobr/rdap/pull/31
https://github.com/registrobr/rdap-client/pull/10
